version: '2'

services:
  janus-gateway:
    image: janus/8x8_0.1
    ports:
      - "800:800"
      - "7088:7088"
      - "8088:8088"
      - "8188:8188"
      - "8089:8089"
      - "10000-10200:10000-10200/udp"
    environment:
      - DOCKER_IP=${DOCKER_IP}
